[package]
name = "yaml_query_native"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "yaml_query_native"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
jql-runner = "7.1.8"
rustler = "0.32.1"
serde_json = "1.0.117"
serde_yaml = "0.9.34"
